[package]
name = "btcnode-metrics"
version = "0.1.0"
edition.workspace = true

[dependencies]
corepc-client.workspace = true
prometheus.workspace = true
serde.workspace = true
toml.workspace = true
thiserror.workspace = true
tracing.workspace = true
