[package]
name = "btcnode-metrics-gatherer"
version = "0.1.0"
edition.workspace = true

[dependencies]
btcnode-metrics = { path = "../btcnode-metrics" }
prometheus.workspace = true
tracing.workspace = true
